// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc691.Robot2018.subsystems;

import org.usfirst.frc691.Robot2018.RobotMap;
import org.usfirst.frc691.Robot2018.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX talonSRXleft1 = RobotMap.drivetrainTalonSRXleft1;
    private final WPI_TalonSRX talonSRXleft2 = RobotMap.drivetrainTalonSRXleft2;
    private final SpeedControllerGroup groupLeft = RobotMap.drivetrainGroupLeft;
    private final WPI_TalonSRX talonSRXright1 = RobotMap.drivetrainTalonSRXright1;
    private final WPI_TalonSRX talonSRXright2 = RobotMap.drivetrainTalonSRXright2;
    private final SpeedControllerGroup groupRight = RobotMap.drivetrainGroupRight;
    private final DifferentialDrive driver = RobotMap.drivetrainDriver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new StickDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    }

    public void drive(Joystick stick) {
    	driver.arcadeDrive(-stick.getY(), stick.getZ(), true);
    	SmartDashboard.putNumber("TL1", talonSRXleft1.get());
    	SmartDashboard.putNumber("TL2", talonSRXleft2.get());
    	SmartDashboard.putNumber("TR1", talonSRXright1.get());
    	SmartDashboard.putNumber("TR2", talonSRXright2.get());
    }
    
    public void driveStop() {
    	driver.stopMotor();
    }
}
