// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.team691.robot2018.subsystems;

import frc.team691.robot2018.RobotMap;
import frc.team691.robot2018.commands.*;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class Elevator extends Subsystem {
	private static final double MOTOR_DRIVE_UP = 1.0;
	private static final double MOTOR_DRIVE_DN = 0.5;
	private static final double MOTOR_AUTO_DRIVE = 0.7;
	private static final double SERVO_RELEASE_POS = 1.0;
	private static final double SERVO_CATCH_POS = 0.43;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController motor1 = RobotMap.elevatorMotor1;
    private final SpeedController motor2 = RobotMap.elevatorMotor2;
    private final SpeedControllerGroup motorGroup = RobotMap.elevatorMotorGroup;
    private final Encoder encoder = RobotMap.elevatorEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Servo servo = RobotMap.intakeServo;

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    @Override
    public void periodic() {
    	SmartDashboard.putNumber("Servo", servo.get());
        SmartDashboard.putNumber("Servo(Angle)", servo.getAngle());
    }
    
    public void drive(double spd) {
    	motorGroup.set(spd);
    }
    
    public void driveDir(int dir) {
    	drive(Math.signum(dir) * MOTOR_AUTO_DRIVE);
    }
    
    public void driveUp(int dir) {
    	drive(dir * MOTOR_DRIVE_UP);
    }
    
    public void driveDown(int dir) {
    	drive(dir * -MOTOR_DRIVE_DN);
    }
    
    public void driveStop() {
    	drive(0);
    }
    
    public void setInverted(boolean i) {
    	motorGroup.setInverted(i);
    }
    
    public void servoSetRelease() {
    	servo.set(SERVO_RELEASE_POS);
    }
    
    public void servoSetCatch() {
    	servo.set(SERVO_CATCH_POS);
    }
}
