// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc691.Robot2018.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc691.Robot2018.Robot;
import org.usfirst.frc691.Robot2018.RobotMap;
import org.usfirst.frc691.Robot2018.subsystems.Drivetrain;

public class StickDrive extends Command {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private Joystick stick;
	private Drivetrain dt;
	private int dmode = 0;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public StickDrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    	stick = Robot.oi.getStick();
    	dt = Robot.drivetrain;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES    	
    	SmartDashboard.putNumber("DriveLeftSpeed", 0);
    	SmartDashboard.putNumber("DriveRightSpeed", 0);
    	SmartDashboard.putNumber("DrivePIDVelocity", 0);
    	SmartDashboard.putNumber("kP", dt.kP);
    	SmartDashboard.putNumber("kI", dt.kI);
    	SmartDashboard.putNumber("kD", dt.kD);
    	SmartDashboard.putNumber("kF", dt.kF);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	dmode = 1;
    	dt.resetEncoders();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	SmartDashboard.putNumber("dmode", dmode);
    	if (stick.getTriggerPressed()) {
    		dt.resetEncoders();
    	}
    	if (stick.getRawButtonPressed(8)) {
    		dmode = (dmode + 1) % 3;
    	}
    	if (stick.getRawButtonPressed(11)) {
    		SmartDashboard.putNumber("DriveLeftSpeed", 0);
        	SmartDashboard.putNumber("DriveRightSpeed", 0);
        	SmartDashboard.putNumber("DrivePIDVelocity", 0);
    	}
    	if (dmode == 0) {
    		dt.driveStick(stick);
    	} else if (dmode == 1) {
    		dt.drive(SmartDashboard.getNumber("DriveLeftSpeed", 0), SmartDashboard.getNumber("DriveRightSpeed", 0));
    	} else {
    		dt.drivePIDVelocity(SmartDashboard.getNumber("DrivePIDVelocity", 0));
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	dt.driveStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
