// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc691.Robot2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivetrainTalonSRXleft;
    public static WPI_TalonSRX drivetrainTalonSRXright;
    public static DifferentialDrive drivetrainDriver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivetrainTalonSRXleftSlave;
    public static WPI_TalonSRX drivetrainTalonSRXrightSlave;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainTalonSRXleft = new WPI_TalonSRX(0);
        
        
        drivetrainTalonSRXright = new WPI_TalonSRX(1);
        
        
        drivetrainDriver = new DifferentialDrive(drivetrainTalonSRXleft, drivetrainTalonSRXright);
        LiveWindow.addActuator("Drivetrain", "Driver", drivetrainDriver);
        drivetrainDriver.setSafetyEnabled(true);
        drivetrainDriver.setExpiration(0.1);
        drivetrainDriver.setMaxOutput(0.8);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainTalonSRXleftSlave = new WPI_TalonSRX(2);
        drivetrainTalonSRXleftSlave.follow(drivetrainTalonSRXleft);
        drivetrainTalonSRXrightSlave = new WPI_TalonSRX(3);
        drivetrainTalonSRXrightSlave.follow(drivetrainTalonSRXright);
    }
}
